### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dantio** [DaniilTomilow/TreasureHuntAR#1]
- [ ] audio upload
- [ ] animate treasure in treasure hunter mode
- [ ] inTreasureArea: ONTAP = Play audio
- [ ] inTreasureArea: SWIPE DOWN - hunting mode
